= Use Case Promotion Package

This section contains links to events where DESIDE has been promoted: +

Canadian Polar Data Workshop V +
May 27–31, 2024, Halifax, Canada +
https://wpsites.ucalgary.ca/canadianpolardataworkshop/cpdw5/

North American Ice Service 22nd Meeting +
June 4, 2024, Ottawa, Canada +
(No website available)

3rd Destination Earth User eXchange +
October 15 - 16, 2024, Darmstadt, Germany +
https://destination-earth.eu/event/3rd-destination-earth-user-exchange/

12th INTERNATIONAL WORKSHOP ON SEA ICE MODELLING, ASSIMILATION, OBSERVATIONS, PREDICTIONS AND VERIFICATION +
5 - 7 November 2024 | ESA,ESRIN | Frascati, Italy +
https://nikal.eventsair.com/iicwg---da---12-workshop-2024/

ESA Digital Twin Earth Components: Open Science Meeting +
3-5 February 2025 | ESRIN | Frascati, Italy +
https://nikal.eventsair.com/esa-digital-twin/#introduction

This section contains the documents in the Use Case Promotion Package

:poster-attachment: https://github.com/destination-earth/DestinE_ESA_DESIDE/blob/main/documents/UCPP/images/DESIDE_Poster.pdf
link:{poster-attachment}[DESIDE Poster]

:slides-attachment: https://github.com/destination-earth/DestinE_ESA_DESIDE/blob/main/documents/UCPP/images/DESIDE_Slides_2.pptx
link:{slides-attachment}[DESIDE Introductory Slides]

:description-attachment: https://github.com/destination-earth/DestinE_ESA_DESIDE/blob/main/documents/UCPP/images/DestinE_Use_Case_DESIDE.docx
link:{description-attachment}[DESIDE Description]

:website-attachment: https://deside.polarview.org/
link:{website-attachment}[DESIDE Website]

This section contains material created for specific events

:slides-attachment: https://github.com/destination-earth/DestinE_ESA_DESIDE/blob/main/documents/UCPP/images/IICWG%202024%20DESIDE.pdf
link:{slides-attachment}[IICWG Workshop Slides]
Presented at IICWG-XXV, September 2024 https://nsidc.org/iicwg/iicwg-meetings

:slides-attachment: https://github.com/destination-earth/DestinE_ESA_DESIDE/blob/main/documents/UCPP/images/DESIDE_RR3.pdf
link:{slides-attachment}[RR3 Slides]

This section contains promotion material created by others

:website-attachment: https://marine.copernicus.eu/services/use-cases/bridging-data-gaps-smarter-arctic-and-antarctic-navigation
link:{website-attachment}[Copernicus Marine Service Use Case]

:website-attachment: https://www.youtube.com/watch?v=aVtes_u7WwQ
link:{website-attachment}[DestinE Use Cases Video]

:website-attachment: https://destination-earth.eu/event/roadshow-webinar-deside/
link:{website-attachment}[DESIDE Webinar]

:website-attachment: https://destination-earth.eu/news/navigating-polar-frontier-deside-use-case/
link:{website-attachment}[DestinE Blog]

